language: scala
jdk:
  # see https://github.com/travis-ci/travis-cookbooks/issues/35
  - oraclejdk7
scala:
  - 2.10.0
before_install:
  - sudo dpkg -r sbt
  - sudo rm /usr/bin/sbt
  # - wget http://files.travis-ci.org/packages/deb/sbt/sbt-0.12.1.deb -O /tmp/sbt.deb
  - sudo dpkg -i /tmp/sbt.deb
script:
  - ./sbt test
