# sbt/travis documentation
# * http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
# * http://docs.travis-ci.com/user/languages/scala/
# * http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
#
# Java flags
# * https://weblogs.java.net/blog/kcpeppe/archive/2013/12/11/case-study-jvm-hotspot-flag

sudo: false

language: scala

script:
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts .travis-jvmopts test

jdk:
  - oraclejdk7

scala:
  - 2.10.4
  - 2.11.5

branches:
  only:
    - /^series/.*$/

## nobody looks at experimental these days so let's save resources
# matrix:
#   include:
#     - script: sbt ++$TRAVIS_SCALA_VERSION experimental/test
#       jdk:    oraclejdk7
#       scala:  2.11.5
#     - script: sbt ++$TRAVIS_SCALA_VERSION experimental/test
#       jdk:    oraclejdk7
#       scala:  2.10.4      
#   allow_failures: 
#    - script: sbt ++$TRAVIS_SCALA_VERSION experimental/test 

notifications:
  irc: "chat.freenode.net#banana-rdf"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/30f837cd3dec6d6230c2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true      # default: false
