# doc: http://about.travis-ci.org/docs/user/languages/scala/
language: scala
jdk:
  # see https://github.com/travis-ci/travis-cookbooks/issues/35
  - oraclejdk7
scala:
  - 2.10.0
#script:
#  - ./sbt test
